influxdb:
  hostname: influxdb.bendews.com
  port: 80
  database: graphite

esxi_hosts:
  - hostname: hm-esx-dell01.bendews.com
    community: public
  - hostname: hm-esx-nuc01.bendews.com
    community: public
  - hostname: hm-esx-nuc02.bendews.com
    community: public

synology_hosts:
  - hostname: hm-data-hp01.bendews.com
    community: public
    volumes:
      - "volume1"
      - "volume2"
      - "volume3"

ipmi_hosts:
  - hostname: R210ii-MGMT.bendews.com
    username: root
    password: 
  - hostname: HPGen8-MGMT.bendews.com
    username: Administrator
    password: 

ups_hosts:
  - hostname: 10.1.1.25
    community: public