influxdb:
  hostname: "InfluxDB.company.com"
  port: "2003"
  database: "easy_influx"
  insert_interval: "30"

esxi_hosts:
  - hostname: "ESXi-01.company.com"
    snmp_community: "public"
    snmp_version: "2c"
  - hostname: "ESXi-01.company.com"
    snmp_community: "public"
    snmp_version: "2c"
  - hostname: "ESXi-03.company.com"
    snmp_community: "public"
    snmp_version: "2c"

synology_hosts:
  - hostname: "Synology-01.company.com"
    snmp_community: "public"
    snmp_version: "2c"
    volumes:
      - "volume1"
      - "volume2"
      - "volume3"

ipmi_hosts:
  - hostname: "Dell-iDRAC.company.com"
    ipmi_username: "root"
    ipmi_password: "password123"
  - hostname: "HP-iLO.company.com"
    ipmi_username: "Administrator"
    ipmi_password: "password123"

ups_hosts:
  - hostname: "UPS.company.com"
    snmp_community: "public"
    snmp_version: "1"